y='\033[1;33m'
w="\033[0m"

import os,sys
import time
import random
#colors
g='\033[1;32m'
p='\033[1;35m'
cyan='\033[1;36m'
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
blue='\033[1;34m'
purple='\033[1;35m'
reset='\033[0m'
y='\033[1;33m'
def sem_1():
 time.sleep(0.01)
 print (red +'')
 time.sleep(0.01)
 print ("")
 print ("")
 print (green +' _____  '+red +' _      ______      ________  '+purple +"__     ______  _    _")
 time.sleep(0.01)
 print (green +'|_   _|' +red +' | |    / __ \ \    / /  ____| '+purple +"\ \   / / __ \| |  | |")
 time.sleep(0.01)
 print (green + '  | |  ' +red +' | |   | |  | \ \  / /| |__    '+purple + " \ \_/ / |  | | |  | |")
 time.sleep(0.01)
 print (green + '  | |  ' +red +' | |   | |  | |\ \/ / |  __|   '+purple + "  \   /| |  | | |  | |")
 time.sleep(0.01)
 print (green +' _| |_  '+red +'| |___| |__| | \  /  | |____  '+purple  +  "   | | | |__| | |__| |")
 time.sleep(0.01)
 print (green +'|_____| '+red +'|______\____/   \/   |______| '+purple   + "   |_|  \____/ \____/")
 time.sleep(0.01)
 print ("")
 print ("")
 print ("")
 time.sleep(0.01)

 print ("")
 print("")
 time.sleep(0.01)
 time.sleep(0.01)

def sem_2():
 
 print (cyan+'''         `://-::.`                          `-++syhs` ''')
 time.sleep( 0.01)
 print (cyan+'''          dNNNNNNNds-                      `odNNmddmm`              ''')
 time.sleep( 0.01)
 print (cyan+'''          /mmmmdddmNdo-                   :hmdhhddmN+               ''')
 time.sleep( 0.01)
 print (cyan+'''           /Nmmdddhhho++`     ''' +red+'OneForAll'+cyan+'''     /hdhhhhhhdm-               ''')
 time.sleep( 0.01)
 print (cyan+'''            hmdhhhyho/s/o.              /ddhhyyyyyhm:               ''')
 time.sleep( 0.01)
 print (cyan+'''            omdyyyso/.-s/s.            .hhdyyyysssyho               ''')
 time.sleep( 0.01)
 print (cyan+'''            omdyyyys+-..o/s```..```.``.oddyyo+/:://oo`              ''')
 time.sleep( 0.01)
 print (cyan+'''            /mddysss+::-.+y/``..``...`.ymhhho/:.-/+s/`              ''')
 time.sleep( 0.01)
 print (cyan+'''            `+ddyyss/---.`sh.``-``...`.hdyyhssss+::::/++:`          ''')
 time.sleep( 0.01)
 print (cyan+'''          -+syyyyyyy:oo:..-y: `````..``dsyyyyhhh/--:+sdNNm:         ''' )
 time.sleep( 0.01)
 print (cyan+'''        .smmdhysosyy.-:...-+y//``  ``:-mdhhhyyysoshddmmNNNN/        ''')
 time.sleep( 0.01)
 print (cyan+'''        ymmdsyyyssso/::-:/+yNd/`     /dNNdyhhhhhshdmmmmmNMMm`       ''')
 time.sleep( 0.01)
 print (cyan+'''       +mmmhosyyyys::+shdmNNd:`.-    ::sdddhddddhhdmmmmmNMN/        ''')
 time.sleep( 0.01)
 print (cyan+'''       oNmmhyyyyhdhhhdhhs/+---``-` ``/.`-.:`:+odh+sydmNMNy-         ''')
 time.sleep( 0.01)
 print (cyan+'''     ``.+mmmmddmmdysmh//-.:--.:.-....:-.---..........:+/-`          ''')
 time.sleep( 0.01)
 print (cyan+'''       ..-ohNNNho::://::://+////::::::::::::-----.......``       ''')
 time.sleep( 0.01)
 print (cyan+'''        `...---------:::::::::::::------------.......````           ''')
 time.sleep( 0.01)
 print (cyan+'''           `````````````...........```````````````````              ''')
 time.sleep(0.01) 
def sem_3():
 
 print (cyan+'''                                       .-.              ''')
 time.sleep(0.01)
 print (cyan+'''                                       : `-`        ''')
 time.sleep(0.01)
 print (cyan+'''                                     -o. .:/-           ''')                                  
 time.sleep(0.01)
 print (cyan+'''                                     -o   ``:/              '''           )
 time.sleep(0.01)
 print (cyan+'''                                    .++      .:             ''')
 time.sleep(0.01)
 print (cyan+'''                                     ./       .-.               '''   )                       
 time.sleep(0.01)
 print (cyan+'''                           '''+red+'OneForAll'+cyan+'''     o..   .  /- -                                     ''')
 time.sleep(0.01)
 print (cyan+'''                        `.`..-:-`    .sh+-.`:- :`:.                                        ''')
 time.sleep(0.01)
 print (cyan+'''                        hshmmmdddhhdmNmooyhhh+:o/:-                         ''')
 time.sleep(0.01)
 print (cyan+'''                       `+smmNmNNmmmNNNdyyhddmNd+.                      ''')
 time.sleep(0.01)
 print (cyan+'''                         .dmmmNNmmmNNNhyyhddddh.                          ''')
 time.sleep(0.01)
 print (cyan+'''                         `hmmhdNmmmNNMmdssshNdy`                                           ''')
 time.sleep(0.01)
 print (cyan+'''                        -dyh:  .//+/sNmso+-+Ndy+                                               ''')
 time.sleep(0.01)
 print (cyan+'''                         s/s.        dy+s  `:::`                                             ''')
 time.sleep(0.01)
 print (cyan+'''                         -so/.`      h/o:                                                         ''')
 time.sleep(0.01)
 print (cyan+'''                         `hsoys` `   s-y/`                                                   ''')
 time.sleep(0.01)
 print (cyan+'''                          -hdh/`````.h:shh+`````                                             ''')
 time.sleep(0.01)
 print (cyan+'''                        ``.--.``````.Ndh:-.`````````````        ''')
 time.sleep(0.01)
 print (cyan+'''                     `````..`````````:/:.```````````````````                                ''')
 time.sleep(0.01)
 print (cyan+'''                `````````....````````.`..```````````````````                                  ''')
 time.sleep(0.01)
 print (cyan+'''               ``````````......``````-`..```````````````````````                            ''')
 time.sleep(0.01)
 print (cyan+'''        ``````````````````...........-...`````````````````````````````````                   ''')
 time.sleep(0.01)
 print (cyan+'''````````````````````````....----.....--...````````````````````````````````                      ''')
 time.sleep(0.01)
 print (cyan+'''````````````````````````.........-------....``````````````````````````````                     ''')
 time.sleep(0.01)
 print (cyan+'''``````````````````````````........------......`````````````````````````````     ''')
 time.sleep(0.01)
 print (cyan+'''````````````````````````````.........---.......````````````````````````````       ''')
 time.sleep(0.01)
 print (cyan+'''````````````````````````````....................```````````````````````````   ''')
 time.sleep(0.01)
 print (cyan+'''````````````````````````........................``````````````````````````` ''')
 time.sleep(0.01)
 print (cyan+'''................````...............................```````````````````````'''   )
 time.sleep(0.01)
 print (cyan+'''................................................................```````'''    )
 time.sleep(0.01)
 print (cyan+'''.........'''+green+'Telegram : https://t.me/kali_linux_ar'+cyan+'''...............................''' )
 time.sleep(0.01)
 print (cyan+'''........................ Dr Data { '''+red+'OneForAll'+cyan+''' } .............................''')         
 time.sleep(0.01)
 print (cyan+'''.....................................................................      ''')
 time.sleep(0.01)                              
def sem_4():
 
 print (red+'''                             `...-........`                   ''')
 time.sleep(0.01)
 print (red+'''                        `-:/::::--------:///-                ''')
 time.sleep(0.01)
 print (red+'''                      .//::::--...```.....--/o:`             ''')
 time.sleep(0.01)
 print (red+'''                    `:+/::::--.`         ``..:oo-            ''')
 time.sleep(0.01) 
 print (red+'''                   `/+////:--.`             `.-+y/           ''')
 time.sleep(0.01)
 print (red+'''                   :+///+/:--..`             `.:+y/          ''')
 time.sleep(0.01)
 print (red+'''                  -+///o+::::--...``         ``-:oy-         ''')
 time.sleep(0.01)
 print (red+'''                 `/+/+/oo/:-----::::-.`      ``.:+ys         ''')
 time.sleep(0.01)
 print (red+'''   -/....        .+o+s/o:.``  `.----//:-``````.::+yy         ''')
 time.sleep(0.01)
 print (red+'''   :+so:`.       .ossh++:.``     `.:--/o/:----:::+ys         ''')
 time.sleep(0.01)
 print (red+'''   `/so.``       `oyhdyosys+:``    .//:/soo++//::sy:         ''')
 time.sleep(0.01)
 print (red+'''   -o//:.`.       `ydy+/-sNdo+:.`  `.s+-/yhyyo+:ohy.         ''')
 time.sleep(0.01)
 print (red+'''  `///sys:```      -+++-`sd-./+o/-` `/s/-oo/::::-.:y+        ''')
 time.sleep(0.01)
 print (red+'''    `````:+-`.`    `:/s/.`//:/:/hy/.`-syo+-..`````/s+        ''')
 time.sleep(0.01)
 print (red+'''          `:+.`.`   `-/++.`-/oshdsoyyyysh/-+shmmo/-`         ''')
 time.sleep(0.01)
 print (red+'''            `+/`.-`  :y++s+:.`.``.:yh+yhomNNNMm/+            ''')
 time.sleep(0.01)
 print (red+'''              -+:`-:-s+:oh++/+++osyoyyhmsysyys-o/       .::.  ''')
 time.sleep(0.01)
 print (red+'''               `/o.`/+:+/ho://://+o/o+oyo+--///-       /y/.:. ''')
 time.sleep(0.01)
 print (red+'''                 .+/.:+s+::o++-/::/://+++o:`        `-+o:`-- ''')
 time.sleep(0.01)
 print (red+'''                   -o/+o++-/Nd/::.-.-:::+/    `.-::::-```.s- ''')
 time.sleep(0.01)
 print (red+'''                    `+ho+/:-dMNMNy:/y+/::`.-:::-```......./: ''')
 time.sleep(0.01)
 print (red+'''                      .o++/:/dNmmm/:++::::.``......`         ''')
 time.sleep(0.01)
 print (red+'''                        /++/::::++/+/-.`.--..`               ''')
 time.sleep(0.01)
 print (red+'''                        `+s+/+/:/+s-::--`                    ''')
 time.sleep(0.01)
 print (red+'''                    `.:///oyo+++//+`                         ''')
 time.sleep(0.01)
 print (red+'''                .-:::-..-:++---://-:`                        ''')
 time.sleep(0.01)
 print (red+'''           `-:::-``----.`      `:o:`--`                      ''')
 time.sleep(0.01)
 print (red+'''   `....-:/:-``---.`             `:+:.-.                     ''')
 time.sleep(0.01)
 print (red+'''  --`..-..``--.`                   `-+-.-.                   ''')
 time.sleep(0.01)
 print (red+''' `+/:/:```-.           '''+cyan+'OneForAll'+red+'''        `:/..:-`                ''')
 time.sleep(0.01)
 print (red+'''    `/y- -`           '''+cyan+'Dr Data'+red+'''         `/+/.....-            ''')
 time.sleep(0.01)
 print (red+'''     `++:.                               +o```-::            ''')
 time.sleep(0.01)
 print (red+'''                                         `+/:/-              ''')
 time.sleep(0.01)
def sem_5():
 
 time.sleep(0.01)
 print (cyan+'                          ````....````')
 time.sleep(0.01)
 print (cyan+'                    `.:oyhmNMMMMMMMMNmdyo/-`')
 time.sleep(0.01)
 print (cyan+'                `./ymMMMMMMNNMMMMMMMNMMMMMMNho-`')
 time.sleep(0.01)
 print (cyan+'              .+hMMMMMMMMMM+ .::/:. -MMMMMMMMMMdo-`' )
 time.sleep(0.01)
 print (cyan+'           `.sNMMMMMMMMMMMm          dMMMMMMMMMMMMy:`')
 time.sleep(0.01)
 print (cyan+'          .oNMMMMMMMMMMMMM/          /MMMMMMMMMMMMMMy-`')
 time.sleep(0.01)
 print (cyan+'        `:mMMMMMMMMMMMMMMm::::::::::::NMMMMMMMMMMMMMMN+`')
 time.sleep(0.01)
 print (cyan+'       `+MMMMMMMMMMMMMMmssssssssssssssssNMMMMMMMMMMMMMMy.')
 time.sleep(0.01)
 print (cyan+'      `oMMMMMMMMMMMMNy/..----:::::-----..+dMMMMMMMMMMMMMh.')
 time.sleep(0.01)
 print (cyan+'     `/MMMMMMMMMMMMMMMMMs.   `-+:`   `:NMMMMMMMMMMMMMMMMMs`')
 time.sleep(0.01)
 print (cyan+'     .mMMMMMMMMMMMMMMMMM+    `/ms.    .NMMMMMMMMMMMMMMMMMM:')
 time.sleep(0.01)
 print (cyan+'    `+MMMMMMMMMMMMMMMMMMMdyydMMMMMmhyhNMMMMMMMMMMMMMMMMMMMh`')
 time.sleep(0.01)
 print (cyan+'    `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.')
 time.sleep(0.01) 
 print (cyan+'    `mMMMMMMMMMMMMMMMMMMN+mMMMMMMMMMNsyMMMMMMMMMMMMMMMMMMMM-')
 time.sleep(0.01)
 print (cyan+'    `dMMMMMMMMMMMMMMMMMMy  :hMMMMMmo` :MMMMMMMMMMMMMMMMMMMM-')
 time.sleep(0.01)
 print (cyan+'    `yMMMMMMMMMMMMMMMMMM+  `oMMMMMh-  `MMMMMMMMMMMMMMMMMMMN.')
 time.sleep(0.01)
 print (cyan+'     /MMMMMMMMMNdyo+/:::` oNMMMMMMMMh- :::/+oshmMMMMMMMMMMy`')
 time.sleep(0.01)
 print (cyan+'     .dMMMMMMy.          :MMMN`  :MMMy          `/NMMMMMMN-')
 time.sleep(0.01)
 print (cyan+'      :NMMMMN           sMMMMMh .mMMMMd.          oMMMMMMo`')
 time.sleep(0.01)
 print (cyan+'      `/NMMMm           :NMMMMo  dMMMMh           +MMMMMs`')
 time.sleep(0.01)
 print (cyan+'       `:NMMM`           -NMMN.  /MMMd`  `:V/     yMMMMo`')
 time.sleep(0.01)
 print (cyan+'         -hMM+            .mMy    mMd`  ./+++:   `NMMm/`')
 time.sleep(0.01)
 print (cyan+'          `/mm             .m.    +m`            oMNo.')
 time.sleep(0.01)
 print (cyan+'            `+-             `     `.            `do.')
 time.sleep(0.01)
 print (cyan+'              ```       '+green+'DrData'+cyan+'{'+red+'OneForAll'+cyan+'}         `.`')
 time.sleep(0.01)
 print (cyan+'                 ````                      ````')
 time.sleep(0.01)
 print (cyan+'                    ``.:+osyhhhhhhyys+/-```')
 time.sleep(0.01)
 print (cyan+'                            ```````')
 time.sleep(0.01)
def sem_6():
 
 print (cyan+"                      _____________________")
 time.sleep(0.01)
 print (cyan+"                     (  "+blue+ 'DrData'+cyan+ '##### '+red+ ' DrData'+cyan+" )")
 time.sleep(0.01)
 print (cyan+"                  /_~~~~~~~~~~~~~~~~~~~~~~~~~_\ ")
 time.sleep(0.01)
 print (cyan+"                /~                             ~\ ")
 time.sleep(0.01)
 print (cyan+'              .~             '+green+'OneForAll'+cyan+'             ~')
 time.sleep(0.01)
 print (cyan+"          ()\/_____                           _____\/() ")
 time.sleep(0.01)
 print (cyan+"         .-``      ~~~~~~~~~~~~~~~~~~~~~~~~~~~     ``-. "      )
 time.sleep(0.01)
 print ('      .-~              ____'+yellow+'I Love you'+cyan+'____             ~-.'  )
 time.sleep(0.01)
 print (cyan+"      `~~/~~~~~~~~~~~~TTTTTTTTTTTTTTTTTTTT~~~~~~~~~~~~\~~` ")
 time.sleep(0.01)
 print (cyan+'      | | |'+green+' #### #### '+cyan+'|| | | | [] | | | || '+green+'#### ####'+cyan+' | | |'  )
 time.sleep(0.01)
 print (cyan+"      ;__\|___________|++++++++++++++++++|___________|/__;")
 time.sleep(0.01)
 print (cyan+"       (~~====___________________________________====~~~)")
 time.sleep(0.01)
 print (cyan+"        \------_____________[Dr Data]__________-------/")
 time.sleep(0.01)
 print (cyan+"           |      ||         ~~~~~~~~       ||      |")
 time.sleep(0.01)
 print (cyan+"            \_____/                          \_____/")
 time.sleep(0.01)
def sem_7():
 
 print( '')
 time.sleep(0.01)
 print (cyan+"""                     _---------.""")
 time.sleep(0.01)
 print (cyan+"""                 .' #######   ;." """)
 time.sleep(0.01)
 print (cyan+"""      .---,.    ;@             @@`;   .---,.. """)
 time.sleep(0.01)
 print (cyan+"""    ." @@@@@'.,'@@            @@@@@',.'@@@@ ". """)
 time.sleep(0.01)
 print (cyan+"""    '-.@@@@@@@@@@@@@          @@@@@@@@@@@@@ @;""")
 time.sleep(0.01)
 print (cyan+"""       `.@@@@@@@@@@@@        @@@@@@@@@@@@@@ .'""")
 time.sleep(0.01)
 print (cyan+"""         "--'.@@@  -.@        @ ,'-   .'--" """)
 time.sleep(0.01)
 print (cyan+"""              ".@' ; @       @ `.  ;'""")
 time.sleep(0.01)
 print (cyan+"""                |@@@@ @@@     @    .""")
 time.sleep(0.01)
 print (cyan+"""                 ' @@@ @@   @@    ,""")
 time.sleep(0.01)
 print (cyan+"""                  `.@@@@    @@   .""")
 time.sleep(0.01)
 print (cyan+"""                    ',@@     @   ;           _____________""")
 time.sleep(0.01)
 print (cyan+"""                     (   3 C    )     /|___ / """+red+"Dr Data !"+cyan+""" \ """)
 time.sleep(0.01)
 print (cyan+"""                     ;@'. __*__,."    \|--- \_____________/ """)
 time.sleep(0.01)
 print (cyan+"""                      '(.,...."/ """)
 time.sleep(0.01)
 print ('')
def sem_8():
 
 time.sleep(0.01)
 print (cyan +'          _____________________________________________    ')
 time.sleep(0.01)           
 print (cyan +'         !\___________________________________________/!\ ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !! \ ')
 time.sleep(0.01)          
 print (cyan +'         !!           Welcome to { '+red+'OneForAll'+cyan+' }           !!  \ ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !!  ! ')
 time.sleep(0.01)
 print (cyan +'         !!                                           !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!  version :  { '+red+'2.0.1'+cyan+' }                     !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!  programmer :  { '+red+'Dr Data'+cyan+' }                !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !!  ! ')
 time.sleep(0.01)        
 print (cyan +'         !!  Telegram :  { '+red+'@kali_linux_ar'+cyan+' }         !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !!  ! ')
 time.sleep(0.01)         
 print (cyan +'         !!                                           !!  / ')
 time.sleep(0.01)        
 print (cyan +'         !!___________________________________________!! / ')
 time.sleep(0.01)        
 print (cyan +'         !/___________________________________________\!/ ')
 time.sleep(0.01)        
 print (cyan +'            __\_____________________________________/__/!_ ')
 time.sleep(0.01)           
 print (cyan +'           !_________________________________________!/    '       )
 time.sleep(0.01)           
 print (cyan +'              _____________________________________    ')
 time.sleep(0.01)              
 print (cyan +'            /oooo  oooo  oooo  oooo  oooo  oooo /!      '    )
 time.sleep(0.01)           
 print (cyan +'           /ooooooooooooooooooooooooooooooooooo/ / ')
 time.sleep(0.01)           
 print (cyan +'          /ooooooooooooooooooooooooooooooooooo/ / ')
 time.sleep(0.01)         
 print (cyan +'         /ooooooooooooooooooooooooooooooooooo/ / ')
 time.sleep(0.01)        
 print (cyan +'        /C=_________________________________/_/ ')
 time.sleep(0.01)
def sem_9():
 
 time.sleep(0.01)
 print (red+'                        ..:::::::::..       ')
 time.sleep(0.01)
 print (red+'                    ..:::aad8888888baa:::..      ' )
 time.sleep(0.01)
 print (red+'                .::::d:?88888888888?::8b::::.      ')
 time.sleep(0.01)
 print (red+'              .:::d8888:?88888888??a888888b:::.      '  )
 time.sleep(0.01)
 print (red+'            .:::d8888888a8888888aa8888888888b:::.      ')
 time.sleep(0.01)
 print (red+'           ::::dP::::::::88888888888::::::::Yb::::     ')
 time.sleep(0.01)
 print (red+'          ::::dP:::::::::Y888888888P:::::::::Yb::::     ')
 time.sleep(0.01)
 print (red+'         ::::d8:::::::::::Y8888888P:::::::::::8b::::     ' )
 time.sleep(0.01)
 print (red+'        .::::88::::::::::::Y88888P::::::::::::88::::.     ')
 time.sleep(0.01)
 print (red+'        :::::Y8baaaaaaaaaa88P:T:Y88aaaaaaaaaad8P:::::      ')
 time.sleep(0.01)
 print (red+'        :::::::Y88888888888P::|::Y88888888888P:::::::     ')
 time.sleep(0.01)
 print (red+'        ::::::::::::::::888:::|:::888::::::::::::::::     ')
 time.sleep(0.01)
 print (red+"        `:::::::::::::::8888888888888b::::::::::::::'   ")
 time.sleep(0.01)
 print (red+'         :::::::::::::::88888888888888::::::::::::::   ')
 time.sleep(0.01)
 print (red+'          :::::::::::::d88888888888888:::::::::::::   ')
 time.sleep(0.01)
 print (red+'           ::::::::::::88::88::88:::88::::::::::::  ')
 time.sleep(0.01)
 print (red+"            `::::::::::88::88::88:::88::::::::::'  ")
 time.sleep(0.01)
 print (red+"              `::::::::88::88::P::::88::::::::'  ")
 time.sleep(0.01)
 print (red+"                `::::::88::88:::::::88::::::'  ")
 time.sleep(0.01)
 print (red+"                   ``:::::::::::::::::::''  ")
 time.sleep(0.01)
 print (red+"                        ``:::::::::''  ")
 time.sleep(0.01)
def sem_10():
 
 time.sleep(0.01)
 print (cyan +"""                     ,                """)
 time.sleep(0.01)
 print (cyan +"""                     |'.             , """)
 time.sleep(0.01)
 print (cyan +"""                     |  '-._        / ) """)
 time.sleep(0.01)
 print (cyan +"""                   .'  .._  ',     /_'-,  """)
 time.sleep(0.01)
 print (cyan +"""                  '   /  _'.'_\   /._)')  """)
 time.sleep(0.01)
 print (red +"""                 :   /  '_' '_'  /  _.' """)
 time.sleep(0.01)
 print (red +"""                 |E |   |Q| |Q| /   / """)
 time.sleep(0.01)
 print (red +"""               .'  _\  '-' '-'    / """)
 time.sleep(0.01)
 print (red +"""              .'--.(S     ,__` )  /    """)
 time.sleep(0.01) 
 print (red +"""                    '-.     _.'  /      """)
 time.sleep(0.01)
 print (green +"""                  __.--'----(   /   """ ) 
 time.sleep(0.01)
 print (green +"""              _.-'     :   __\ / """)
 time.sleep(0.01)
 print (green +"""             (      __.' :'  :Y """)
 time.sleep(0.01)
 print (green +"""              '.   '._,  :   :|        """)
 time.sleep(0.01)
 print (cyan +"""                '.     ) :.__:|      """)
 time.sleep(0.01)
 print (cyan +"""                  \    \______/ """)
 time.sleep(0.01)
 print (cyan +"""                   '._D/_Z____]    """)                                       
 time.sleep(0.01)
def sem_11():
 
 time.sleep(0.01)
 print (cyan +"""                            _...----.                """)
 time.sleep(0.01)
 print (cyan +"""                          .'    .-'`                """)
 time.sleep(0.01)
 print (cyan +"""                        ,''--..;                 """)
 time.sleep(0.01)
 print (cyan +"""                       /       |                  """)
 time.sleep(0.01)
 print (cyan +"""               _______/________|_______               """)
 time.sleep(0.01)
 print (cyan +"""              `-----/// _\  /_ \\\-----`                  """)
 time.sleep(0.01)
 print (cyan +"""                .---./ / o\/o \ \.---.                  """)
 time.sleep(0.01)
 print (cyan +"""               <(_ /// \__/\__/ \\\ _)>   _.---.                  """)
 time.sleep(0.01)
 print (cyan +"""                '-. //    oo    \\ .-'  .'   .__`\                  """)
 time.sleep(0.01)
 print (cyan +"""             o    /// __..--..__ \\\   /       \`\|                  """)
 time.sleep(0.01)
 print (cyan +"""          o-'*'-o //| '\/\/\/\/' |\\  /         ; '                  """)
 time.sleep(0.01)
 print (cyan +"""          \*\|/*/   ;--. """"  .-;   |   _   _  |                  """)
 time.sleep(0.01)
 print (cyan +"""         .-'---'-. / \|||-....(|||`\ |  (o) (o) |                  """)
 time.sleep(0.01)
 print (cyan +"""        /         \ /\           /\|/           |                  """)
 time.sleep(0.01)
 print (cyan +"""        |  .---,  |/  \         /  ;  '         |                  """)
 time.sleep(0.01)
 print (cyan +"""        | / e e \ |    '.     .'   |   '-.       \                  """)
 time.sleep(0.01)
 print (cyan +"""         \|  ^  |/       '---'     |              \_                  """)
 time.sleep(0.01)
 print (cyan +"""         ()._-_.()     T R I C K   |     .._.----/` \                  """)
 time.sleep(0.01)
 print (cyan +"""        ,/\'._.'/\. '  .           |    /   ``"-/||\ \                  """)
 time.sleep(0.01)
 print (cyan +"""       / \/     \/ \     O R       |   |            `7,                  """)
 time.sleep(0.01)
 print (cyan +"""      |  ^^_____^^  |              | . /// _          |                  """)
 time.sleep(0.01)
 print (cyan +"""      |oOO`     `OOo|  T R E A T   ; |' / |_) _       |                  """)
 time.sleep(0.01)
 print (cyan +"""      \| '._____.' |/             /  \-|  |_)/ \ _    |                  """)
 time.sleep(0.01)
 print (cyan +"""       |::         | '.__     __,;    `|     \_// \   |                  """)
 time.sleep(0.01)
 print (cyan +"""       |::         |     `````   |     |        \_/  ;                  """)
 time.sleep(0.01)
 print (cyan +"""       |::         |             |      \           /                  """)
 time.sleep(0.01)
 print (cyan +"""       \::.        /_____________|       ``'--..___/                  """)
 time.sleep(0.01)
 print (cyan +"""        '._______.' '-|   |   |-'                 |                  """)
 time.sleep(0.01)
 print (cyan +"""          |_ | _|     |   |   |               __.-;                  """)
 time.sleep(0.01)
 print (cyan +"""          \  |  /     /-._|_.-\                    \                  """)
 time.sleep(0.01)
 print (cyan +"""           \_|_/     /`'-.|.-'`\                   /                  """)
 time.sleep(0.01)
 print (cyan +"""     jgs  /--T--\   /    .'.    \'-..____.---''''``                  """)
 time.sleep(0.01)
 print (cyan +"""         (__/ \__)  \____/  \___/                  """)
 time.sleep(0.01)
def sem_12():
 
 time.sleep(0.01)
 print (cyan +"""                             __                """)
 time.sleep(0.01)
 print (cyan +"""                            |  |              """)
 time.sleep(0.01)
 print (cyan +"""                            |  |              """)
 time.sleep(0.01)
 print (cyan +"""                        ___/____\___              """)
 time.sleep(0.01)
 print (cyan +"""                   _- ~              ~  _              """)
 time.sleep(0.01)
 print (cyan +"""                - ~                      ~ -_              """)
 time.sleep(0.01)
 print (cyan +"""              -                               _              """)
 time.sleep(0.01)
 print (cyan +"""            -         /\            /\          _              """)
 time.sleep(0.01)
 print (cyan +"""           -         / *\          / *\          _              """)
 time.sleep(0.01)
 print (cyan +"""          _         /____\        /____\          _              """)
 time.sleep(0.01)
 print (cyan +"""          _                  /\                   _              """)
 time.sleep(0.01)
 print (cyan +"""          _                 /__\                  _              """)
 time.sleep(0.01)
 print (cyan +"""          _      |\                      /|       _              """)
 time.sleep(0.01)
 print (cyan +"""           -     \ `\/\/\/\/\/\/\/\/\/\/' /      _              """)
 time.sleep(0.01)
 print (cyan +"""            -     \                      /      -              """)
 time.sleep(0.01)
 print (cyan +"""              ~    `\/^\/^\/^\/^\/^\/^\/'      ~              """)
 time.sleep(0.01)
 print (cyan +"""                ~                            -~              """)
 time.sleep(0.01)
 print (cyan +"""                 `--_._._._._._._._._._.._--'              """)
 time.sleep(0.01)
def sem_13():
 
 time.sleep(0.01)
 print (cyan +"""                            ........              """)
 time.sleep(0.01)
 print (cyan +"""                            ;::;;::;,              """)
 time.sleep(0.01)
 print (cyan +"""                            ;::;;::;;,              """)
 time.sleep(0.01)
 print (cyan +"""                           ;;:::;;::;;,              """)
 time.sleep(0.01)
 print (cyan +"""           .vnmmnv%vnmnv%,.;;;:::;;::;;,  .,vnmnv%vnmnv,              """)
 time.sleep(0.01)
 print (cyan +"""        vnmmmnv%vnmmmnv%vnmmnv%;;;;;;;%nmmmnv%vnmmnv%vnmmnv              """)
 time.sleep(0.01)
 print (cyan +"""      vnmmnv%vnmmmmmnv%vnmmmmmnv%;:;%nmmmmmmnv%vnmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +"""     vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmnv%vnmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +"""    vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmmmnv%vnmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +"""   vnmmnv%vnmmmmmnv%vnmm;mmmmmmnv%vnmmmmmmmm;mmnv%vnmmmnv%vnmmmnv,              """)
 time.sleep(0.01)
 print (cyan +"""  vnmmnv%vnmmmmmnv%vnmm;  mmmmmnv%vnmmmmmmm;  mmnv%vnmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +"""  vnmmnv%vnmmmmmnv%vn;;    mmmmnv%vnmmmmmm;;    nv%vnmmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +""" vnmmnv%vnmmmmmmnv%v;;      mmmnv%vnmmmmm;;      v%vnmmmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +""" vnmmnv%vnmmmmmmnv%vnmmmmmmmmm;;       mmmmmmmmmnv%vnmmmmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +""" vnmmnv%vnmmmmmmnv%vnmmmmmmmmmm;;     mmmmmmmmmmnv%vnmmmmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +""" vnmmnv%vnmmmmm nv%vnmmmmmmmmmmnv;, mmmmmmmmmmmmnv%vn;mmmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +""" vnmmnv%vnmmmmm  nv%vnmmmmmmmmmnv%;nmmmmmmmmmmmnv%vn; mmmmmnv%vnmmmnv              """)
 time.sleep(0.01)
 print (cyan +""" `vnmmnv%vnmmmm,  v%vnmmmmmmmmmmnv%vnmmmmmmmmmmnv%v;  mmmmnv%vnnmmnv'              """)
 time.sleep(0.01)
 print (cyan +"""  vnmmnv%vnmmmm;,   %vnmmmmmmmmmnv%vnmmmmmmmmmnv%;    mmmnv%vnmmmmnv              """)
 time.sleep(0.01)
 print (cyan +"""   vnmmnv%vnmmmm;;,   nmmm;,              mmmm;;     mmmnv%vnmmmmnv'              """)
 time.sleep(0.01)
 print (cyan +"""   `vnmmnv%vnmmmmm;;,.         mmnv%v;,            mmmmnv%vnmmmmnv'              """)
 time.sleep(0.01)
 print (cyan +"""    `vnmmnv%vnmmmmmmnv%vnmmmmmmmmnv%vnmmmmmmnv%vnmmmmmnv%vnmmmmnv'              """)
 time.sleep(0.01)
 print (cyan +"""      `vnmvn%vnmmmmmmnv%vnmmmmmmmnv%vnmmmmmnv%vnmmmmmnv%vnmmmnv'              """)
 time.sleep(0.01)
 print (cyan +"""          `vn%vnmmmmmmn%:%vnmnmmmmnv%vnmmmnv%:%vnmmnv%vnmnv'              """)
 time.sleep(0.01)
def sem_14():
 
 time.sleep(0.01)
 print (cyan +"""                        aa@@@@@@@@@@@@@aa              """)
 time.sleep(0.01)
 print (cyan +"""                     a@@@@@@@@@@@@@@@@@@@@@a              """)
 time.sleep(0.01)
 print (cyan +"""                   a@@@@@@@@@@@@@@@@@@@@@@@@@a              """)
 time.sleep(0.01)
 print (cyan +"""                  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                 @@@@@@@~~~~@@@@@@@@@~~~~@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                 @@@@@@      @@@@@@@      @@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                 @@@@@@@aaaa@@@@@@@@@aaaa@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                 `@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'              """)
 time.sleep(0.01)
 print (cyan +"""                  @@@@@@@@~@@@~@@@~@@@~@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                   @@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                    @@@@@@@@~@@@~@@@~@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                     @@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                      @@@@@@@@~@@@~@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""                       `@@@@@@@@@@@@@@@@@'              """)
 time.sleep(0.01)
 print (cyan +"""                           ~~@@@@@@@~~              """)
 time.sleep(0.01)
def sem_15():
 
 time.sleep(0.01)
 print (cyan +"""                     @@@              """)
 time.sleep(0.01)
 print (cyan +"""                     @@@              """)
 time.sleep(0.01)
 print (cyan +"""                      @@@              """)
 time.sleep(0.01)
 print (cyan +"""                      @@@              """)
 time.sleep(0.01)
 print (cyan +"""              @@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""            @@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""        @@@@@@@@ @@@@@@@@@@@@@@@@ @@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""      @@@@@@@@@   @@@@@@@@@@@@@@   @@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""    @@@@@@@@@@     @@@@@@@@@@@@     @@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""   @@@@@@@@@@       @@@@  @@@@       @@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""   @@@@@@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""   @@@@@@@@@@@@@@@@@@        @@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""   @@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""    @@@@@@@@  @@ @@ @@ @@ @@ @@ @@ @  @@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""      @@@@@@@                        @@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""        @@@@@@  @@ @@ @@ @@ @@ @@ @ @@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""            @@@@@@@@@@@@@@@@@@@@@@@@@@              """)
 time.sleep(0.01)
 print (cyan +"""              @@@@@@@@@@@@@@@@@@@@@@              """)
def sem_16():
 
 time.sleep(0.01)
 print (cyan +"""                                         .,,cccd$$$$$$$$$$$ccc,              """)
 time.sleep(0.01)
 print (cyan +"""                                     ,cc$$$$$$$$$$$$$$$$$$$$$$$$$cc,              """)
 time.sleep(0.01)
 print (cyan +"""                                   ,d$$$$$$$$$$$$$$$$"J$$$$$$$$$$$$$$c,              """)
 time.sleep(0.01)
 print (cyan +"""                                 d$$$$$$$$$$$$$$$$$$,$" ,,`?$$$$$$$$$$$$L              """)
 time.sleep(0.01)
 print (cyan +"""                               ,$$$$$$$$$$$$$$$$$$$$$',J$$$$$$$$$$$$$$$$$b              """)
 time.sleep(0.01)
 print (cyan +"""                              ,$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$i `$h              """)
 time.sleep(0.01)
 print (cyan +"""                              $$$$$$$$$$$$$$$$$$$$$$$$$P'  "$$$$$$$$$$$h $$              """)
 time.sleep(0.01)
 print (cyan +"""                             ;$$$$$$$$$$$$$$$$$$$$$$$$F,$$$h,?$$$$$$$$$$h$F              """)
 time.sleep(0.01)
 print (cyan +"""                             `$$$$$$$$$$$$$$$$$$$$$$$F:??$$$:)$$$$P",. $$F              """)
 time.sleep(0.01)
 print (cyan +"""                              ?$$$$$$$$$$$$$$$$$$$$$$(   `$$ J$$F"d$$F,$F              """)
 time.sleep(0.01)
 print (cyan +"""                               ?$$$$$$$$$$$$$$$$$$$$$h,  :P'J$$F  ,$F,$"              """)
 time.sleep(0.01)
 print (cyan +"""                                ?$$$$$$$$$$$$$$$$$$$$$$$ccd$$`$h, ",d$              """)
 time.sleep(0.01)
 print (cyan +"""                                 "$$$$$$$$$$$$$$$$$$$$$$$$",cdc $$$$"              """)
 time.sleep(0.01)
 print (cyan +"""                        ,uu,      `?$$$$$$$$$$$$$$$$$$$$$$$$$$$c$$$$h              """)
 time.sleep(0.01)
 print (cyan +"""                    .,d$$$$$$$cc,   `$$$$$$$$$$$$$$$$??$$$$$$$$$$$$$$$,              """)
 time.sleep(0.01)
 print (cyan +"""                  ,d$$$$$$$$$$$$$$$bcccc,,??$$$$$$ccf `"??$$$$??$$$$$$$              """)
 time.sleep(0.01)
 print (cyan +"""                 d$$$$$$$$$$$$$$$$$$$$$$$$$h`?$$$$$$h`:...  d$$$$$$$$P              """)
 time.sleep(0.01)
 print (cyan +"""                d$$$$$$$$$$$$$$$$$$$$$$$$$$$$`$$$$$$$hc,,cd$$$$$$$$P"              """)
 time.sleep(0.01)
 print (cyan +"""            =$$?$$$$$$$$P' ?$$$$$$$$$$$$$$$$$;$$$$$$$$$???????",,              """)
 time.sleep(0.01)
 print (cyan +"""               =$$$$$$F       `"?????$$$$$$$$$$$$$$$$$$$$$$$$$$$$$bc              """)
 time.sleep(0.01)
 print (cyan +"""               d$$F"?$$k ,ccc$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$i              """)
 time.sleep(0.01)
 print (cyan +"""        .     ,ccc$$c`""u$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$P",$$$$$$$$$$$$h              """)
 time.sleep(0.01)
 print (cyan +"""     ,d$$$L  J$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" `""$$$??$$$$$$$              """)
 time.sleep(0.01)
 print (cyan +"""   ,d$$$$$$c,"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F       `?J$$$$$$$'              """)
 time.sleep(0.01)
 print (cyan +"""  ,$$$$$$$$$$h`$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F           ?$$$$$$$P""=,              """)
 time.sleep(0.01)
 print (cyan +""" ,$$$F?$$$$$$$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F              3$$$$II"?$h,              """)
 time.sleep(0.01)
 print (cyan +""" $$$$$`$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$P"               ;$$$??$$$,"?"              """)
 time.sleep(0.01)
 print (cyan +""" $$$$F ?$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$P",z'                3$$h   ?$F              """)
 time.sleep(0.01)
 print (cyan +"""        `?$$$$$$$$$$$$$$$??$$$$$$$$$PF"',d$P"                  "?$F              """)
 time.sleep(0.01)
 print (cyan +"""              '''''''''''''     ,z$$$$$$$$$$$$$P              """)
 time.sleep(0.01)
 print (cyan +"""                          J$$$$$$$$$$$$$$F              """)
 time.sleep(0.01)
 print (cyan +"""                         ,$$$$$$$$$$$$$$F              """)
 time.sleep(0.01)
 print (cyan +"""                         :$$$$$c?$$$$PF'              """)
 time.sleep(0.01)
 print (cyan +"""                         `$$$$$$$P              """)
 time.sleep(0.01)
 print (cyan +"""                          `?$$$$F              """)
 time.sleep(0.01)
 
def sem_17():
 
 time.sleep(0.01)
 print (cyan +""" ,                                                               ,              """)
 time.sleep(0.01)
 print (cyan +""" \'.                                                           .'/              """)
 time.sleep(0.01)
 print (cyan +"""  ),\                                                         /,(               """)
 time.sleep(0.01)
 print (cyan +""" /__\'.                                                     .'/__\              """)
 time.sleep(0.01)
 print (cyan +""" \  `'.'-.__                                           __.-'.'`  /              """)
 time.sleep(0.01)
 print (cyan +"""  `)   `'-. \                                         / .-'`   ('              """)
 time.sleep(0.01)
 print (cyan +"""  /   _.--'\ '.          ,               ,          .' /'--._   \              """)
 time.sleep(0.01)
 print (cyan +"""  |-'`      '. '-.__    / \             / \    __.-' .'      `'-|              """)
 time.sleep(0.01)
 print (cyan +"""  \         _.`'-.,_'-.|/\ \    _,_    / /\|.-'_,.-'`._         /              """)
 time.sleep(0.01)
 print (cyan +"""   `\    .-'       /'-.|| \ |.-"   "-.| / ||.-'\       '-.    /`              """)
 time.sleep(0.01)
 print (cyan +"""     )-'`        .'   :||  / -.\\ //.- \  ||:   '.        `'-(              """)
 time.sleep(0.01)
 print (cyan +"""    /          .'    / \\_ |  /o`^'o\  | _// \    '.          \              """)
 time.sleep(0.01)
 print (cyan +"""    \       .-'    .'   `--|  `"/ \"`  |--`   '.    '-.       /              """)
 time.sleep(0.01)
 print (cyan +"""     `)  _.'     .'    .--.; |\__"__/| ;.--.    '.     '._  ('              """)
 time.sleep(0.01)
 print (cyan +"""     /_.'     .-'  _.-'     \\ \/^\/ //     `-._  '-.     '._\              """)
 time.sleep(0.01)
 print (cyan +"""     \     .'`_.--'          \\     //          `--._`'.     /              """)
 time.sleep(0.01)
 print (cyan +"""      '-._' /`            _   \\-.-//   _            `\ '_.-'              """)
 time.sleep(0.01)
 print (cyan +"""          `<     _,..--''`|    \`"`/    |`''--..,_     >`              """)
 time.sleep(0.01)
 print (cyan +"""           _\  ``--..__   \     `'`     /   __..--``  /_              """)
 time.sleep(0.01)
 print (cyan +"""          /  '-.__     ``'-;    / \    ;-'``     __.-'  \              """)
 time.sleep(0.01)
 print (cyan +"""         |    _   ``''--..  \'-' | '-'/  ..--''``   _    |              """)
 time.sleep(0.01)
 print (cyan +"""         \     '-.       /   |/--|--\|   \       .-'     /              """)
 time.sleep(0.01)
 print (cyan +"""          '-._    '-._  /    |---|---|    \  _.-'    _.-'              """)
 time.sleep(0.01)
 print (cyan +"""              `'-._   '/ / / /---|---\ \ \ \'   _.-'`              """)
 time.sleep(0.01)
 print (cyan +"""                   '-./ / / / \`---`/ \ \ \ \.-'              """)
 time.sleep(0.01)
 print (cyan +"""                       `)` `  /'---'\  ` `(`              """)
 time.sleep(0.01)
 print (cyan +"""                 jgs  /`     |       |     `\              """)
 time.sleep(0.01)
 print (cyan +"""                     /  /  | |       | |  \  \              """)
 time.sleep(0.01)
 print (cyan +"""                 .--'  /   | '.     .' |   \  '--.              """)
 time.sleep(0.01)
 print (cyan +"""                /_____/|  / \._\   /_./ \  |\_____\              """)
 time.sleep(0.01)
 print (cyan +"""               (/      (/'     \) (/     `\)      \)              """)
 time.sleep(0.01)

def sem_18():
 
 time.sleep(0.01)
 print (cyan +"""                        ,mmmmm,            ______     _________              """)
 time.sleep(0.01)
 print (cyan +"""                        @ooooo@,         / /. . \\   /./-----\.\              """)
 time.sleep(0.01)
 print (cyan +"""                        @0m0m0Q@        / /. . .`,\\>./,  ,  ,\.\              """)
 time.sleep(0.01)
 print (cyan +"""                        @0X00X@@       | |. . .  |:|\|   ,  ,  |.|              """)
 time.sleep(0.01)
 print (cyan +"""                     ____@0m00@_____   | | . . . |:|X| ,  ,  , |.|              """)
 time.sleep(0.01)
 print (cyan +"""                    @@@op(oboy)pop@@Ok | |. . .  |:|\|   ,  ,  |.|              """)
 time.sleep(0.01)
 print (cyan +"""                   @@@@opopopopop@@@p@@| | . . . |:|\| ,  ,  , |.|              """)
 time.sleep(0.01)
 print (cyan +"""                   @@o@@opopopopop@@op@@,|. . .  |:|\|   ,  ,  |.|              """)
 time.sleep(0.01)
 print (cyan +"""                   @@o@@popopopopopop@o@@| . . . |:|X| ,  ,  , |.|              """)
 time.sleep(0.01)
 print (cyan +"""                    @@o@@mmmmmmgogogo@oo@|. . .  |:|\|   ,  ,  |.|              """)
 time.sleep(0.01)
 print (cyan +"""                     @@@@@@@mmm'ooo@|@oo@| . . . |:|\| ,  ,  , |.|              """)
 time.sleep(0.01)
 print (cyan +"""                      @oooooooOOOO@"  @o@|. . .  |:|\|   ,  ,  |.|              """)
 time.sleep(0.01)
 print (cyan +"""                      @OoOoO@OoOoO@   @@@| . . . |:|X| ,  ,  , |.|              """)
 time.sleep(0.01)
 print (cyan +"""                      @oooo@@@oooo@   @@@|. . . .|:|\|   ,  ,  |.|              """)
 time.sleep(0.01)
 print (cyan +"""                     .@@@o@@@@ooo@@  ,@@}| . . .//  \\_________/.|              """)
 time.sleep(0.01)
 print (cyan +"""                    .@@oo@@@@@@ooo@. "@@'|. . //     \==========/              """)
 time.sleep(0.01)
 print (cyan +"""                   .@ooooo@@@@@oooo@      \ //              """)
 time.sleep(0.01)
 print (cyan +"""                   @ooooO@' `@@ooo@|              """)
 time.sleep(0.01)
 print (cyan +"""                   @oooo@'   `@oooo@              """)
 time.sleep(0.01)
 print (cyan +"""                  @ooo@'     `oooo@|                    """)
 time.sleep(0.01)
 print (cyan +"""                  @oo@@'      `@oo@|                    """)
 time.sleep(0.01)
 print (cyan +"""                  @o@@|        @@o@,                         """)
 time.sleep(0.01)
 print (cyan +"""                  @@@@:        @@o@|                              """)
 time.sleep(0.01)
 print (cyan +"""                  @@@@:        @@o@|                        """)
 time.sleep(0.01)
 print (cyan +"""                  `@oo:        `@@@:              """)
 time.sleep(0.01)
 print (cyan +"""                  /@@@)        /@@@)              """)
 time.sleep(0.01)
 print (cyan +"""                (@@@@/       (@@@@/                        """)
 time.sleep(0.01)
b='\033[;94m'
r='\033[1;31m'
red='\033[1;31m'
y='\033[1;33m'
re='\033[0m'
gr='\033[1;32m'
purple='\033[1;35m'
def O2():
	print(f"""
{b}=[{y} One For All  > Exploit v2.0.1-dev       {b}]
+ -- --=[ {gr}500{r} exploits {gr}5 {r}payloads{b} ]
+ -- --=[{gr} 3 {r}ransomwares                  {b}  ]
+ -- --=[          {purple}[ {r} Exit {gr} {purple} ]    {b} ]
""")
O2()
 
 
def sem():
	
	e = str(random.randint(1,18))
	if e in "1":
		sem_2()
	elif e in "2":
		sem_3()
	elif e in "3":
		sem_4()
	elif e in "4":
		sem_5()
	elif e in "5":
		sem_6()
	elif e in "6":
		sem_7()
	elif e in "7":
		sem_8()
	elif e in "8":
		sem_9()
	elif e in "9":
		sem_10()
	elif e in "10":
		sem_11()
	elif e in "11":
		sem_12()
	elif e in "12":
		sem_13()
	elif e in "13":
		sem_14()
	elif e in "14":
		sem_15()
	elif e in "15":
		sem_16()
	elif e in "16":
		sem_17()
	elif e in "17":
		sem_18()
	elif e in "18":
		sem_10()
	else :
	   print ("error")

#sem_10()

